server: {}
tinkerforge:
  endpoints: #[]
    - address: 10.192.64.23
google-sheet:
  key_file: sa-development.json
  spreadsheet_id: 1a2OKCYMOUxE7PfjLjPgvIAf7WY9Y6uTMiXkEKHLlDoo
  endpoints:
    sheet: Tinkerforge Endpoints
    range: A:E
    address: IP-Address
    state: Status
    place: Place
  light_templates:
    sheet: Templates
    range: A:D
    name_column: Name
    discriminator_column: Typ
    temperature_warm_column: Lichttemperatur Warm
    temperature_cold_column: Lichttemperatur Kalt
  light:
    sheet: Lichter
    range: A:T
    room_id: Raum Nummer
    light_id: Id
    light_idx: Idx
    template: Typ
    device_address: DMX
    bus_start_address: Startadresse
    manual_buttons:
      - Taster 1
      - Taster 2
      - Taster 3
    presence_detectors:
      - Bewegungsmelder 1
      - Bewegungsmelder 2
      - Bewegungsmelder 3
    touchscreen_whitebalance: Touchscreen Farbe
    touchscreen_brightness: Touchscreen Helligkeit
    state: Status
  button_templates:
    sheet: Taster Modelle
    range: A:G
    name: Name
    discriminator: Typ
    sub_devices: variants
  buttons:
    sheet: Taster
    range: A:J
    room_id: Raum Nummer
    button_id: id
    button_idx: Idx
    button_type: Typ
    device_address: IO-16 Bricklet
    first_input_idx: Start-Position
    state: Status
  room_controllers:
    sheet: Touchscreen / Temperaturfühler
    range: A:N
    room_id: Raum Nummer
    controller_id: id
    controller_idx: Idx
    orientation: Orientation
    touchscreen_device_address: Adresse Touchscreen
    temperature_device_address: Adresse Temperaturfühler
    enable_heat_control: Heizkreise
    enable_whitebalance_control: Farbe
    enable_brightness_control: Helligkeit
    touchscreen_state: Status Touchscreen
    temperature_state: Status Temperaturfühler
  motion_detectors:
    sheet: Bewegungsmelder
    range: A:I
    room_id: Raum Nummer
    device_address: Adresse
    id: id
    idx: Idx
    state: Status
  relays:
    sheet: Relay
    range: A:L
    room_id: Raum Nummer
    id: id
    idx: Idx
    device_address: Relay Bricklet
    device_channel: Position
    temperature_sensor: Fühler
    ring_button: Taster
    state: Status
  available_bricklets:
    sheet: Verfügbare Geräte
    range: A:M
    endpoint: Endpoint
    master_id: Master Brick
    uid: Adresse
    connector: Stecker
    device_type: Typ
    hardware_version: Hardware
    firmware_version: Firmware
    io_ports: IO Ports
    motion_detectors: Bewegungsmelder
    temp_sensor: Temparatur Sensor
    display: Display
    dmx_channels: DMX Kanäle
    relays: Relays
