server: { }
tinkerforge:
  endpoints: [ ]
  #- address: 10.192.64.23
  #- address: 10.192.66.26
  #- address: 127.0.0.1
shelly:
  endpoints: [ ]
  #- address: 10.192.5.6
google-sheet:
  key_file: sa-development.json
  spreadsheet_id: 107qejIW-1g04V3YhxrRQtNYg0m9zMAPf74A3ISNlxvw
  timestamp_format: '%d.%b %H:%M'
  tinkerforge_endpoints:
    sheet: Tinkerforge Endpoints
    range: A:F
    address: IP-Address
    state: Status Dev
    place: Place
  shelly_endpoints:
    sheet: Shelly Endpoints
    range: A:F
    address: IP-Address
    state: Status Dev
    place: Place
  light_templates:
    sheet: Templates
    range: A:D
    name_column: Name
    discriminator_column: Typ
    temperature_warm_column: Lichttemperatur Warm
    temperature_cold_column: Lichttemperatur Kalt
  light_tinkerforge:
    sheet: Lichter
    range: A:U
    room_id: Raum Nummer
    light_id: Id
    light_idx: Idx
    template: Typ
    device_address: DMX
    bus_start_address: Startadresse
    manual_buttons:
      - Taster 1
      - Taster 2
      - Taster 3
    presence_detectors:
      - Bewegungsmelder 1
      - Bewegungsmelder 2
      - Bewegungsmelder 3
    touchscreen_whitebalance: Touchscreen Farbe
    touchscreen_brightness: Touchscreen Helligkeit
    state: Status Dev
  light_shelly:
    sheet: Lichter
    range: A:U
    room_id: Raum Nummer
    light_id: Id
    light_idx: Idx
    template: Typ
    device_name: Dimmer
    start_idx: Anschluss
    manual_buttons:
      - Taster 1
      - Taster 2
      - Taster 3
    presence_detectors:
      - Bewegungsmelder 1
      - Bewegungsmelder 2
      - Bewegungsmelder 3
    touchscreen_whitebalance: Touchscreen Farbe
    touchscreen_brightness: Touchscreen Helligkeit
    state: Status Dev
  button_templates:
    sheet: Taster Modelle
    range: A:H
    name: Name
    discriminator: Typ
    sub_devices: variants
  buttons:
    sheet: Taster
    range: A:L
    room_id: Raum Nummer
    button_id: id
    button_idx: Idx
    button_type: Typ
    device_address: IO-16 Bricklet
    first_input_idx: Start-Position
    state: Status Dev
  room_controllers:
    sheet: Touchscreen / Temperaturfühler
    range: A:P
    room_id: Raum Nummer
    controller_id: id
    controller_idx: Idx
    orientation: Orientation
    touchscreen_device_address: Adresse Touchscreen
    temperature_device_address: Adresse Temperaturfühler
    enable_heat_control: Heizkreise
    enable_whitebalance_control: Farbe
    enable_brightness_control: Helligkeit
    touchscreen_state: Status Touchscreen Dev
    temperature_state: Status Temperaturfühler Dev
  motion_detectors:
    sheet: Bewegungsmelder
    range: A:K
    room_id: Raum Nummer
    device_address: Adresse
    id: id
    idx: Idx
    state: Status Dev
  relays:
    sheet: Relay
    range: A:M
    room_id: Raum Nummer
    id: id
    idx: Idx
    device_address: Relay Bricklet
    device_channel: Position
    temperature_sensor: Fühler
    ring_button: Taster
    state: Status Dev
  available_bricklets:
    sheet: Verfügbare Bricklets Dev
    range: A:O
    endpoint: Endpoint
    master_id: Master Brick
    uid: Adresse
    connector: Stecker
    device_type: Typ
    hardware_version: Hardware
    firmware_version: Firmware
    io_ports: IO Ports
    motion_detectors: Bewegungsmelder
    temp_sensor: Temparatur Sensor
    display: Display
    dmx_channels: DMX Kanäle
    relays: Relays
    connection_failed_counters: Unterbrüche
    errors: Fehler
  available_shelly_components:
    sheet: Verfügbare Shelly Komponenten Dev
    range: A:C
    device: Gerät
    address: Adresse
    component_type: Typ