FROM ghcr.io/koa/rust-cross-compile:0.0.3 as rust
ADD . /build/
WORKDIR /build
RUN cargo build --release --target x86_64-unknown-linux-musl
FROM scratch as target
COPY --from=rust /etc/ssl /etc/ssl
COPY --from=rust /build/target/x86_64-unknown-linux-musl/release/tf_bridge_rust /
EXPOSE 8080/tcp
ENTRYPOINT ["/tf_bridge_rust"]