FROM ghcr.io/koa/rust-cross-compile:0.0.1 as rust
ADD . /build/
WORKDIR /build
RUN cargo build --release --target armv7-unknown-linux-musleabihf
FROM scratch as target
COPY --from=rust /etc/ssl /etc/ssl
COPY --from=rust /build/target/armv7-unknown-linux-musleabihf/release/tf_bridge_rust /
EXPOSE 8080/tcp
ENTRYPOINT ["/tf_bridge_rust"]