name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta x86
        id: meta-x86
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/koa/tf-bridge-rust
          tags: |
            type=schedule,suffix=-x86
            type=ref,event=branch,suffix=-x86
            type=ref,event=pr,suffix=-x86
            type=semver,pattern={{version}},suffix=-x86
            type=semver,pattern={{major}}.{{minor}},suffix=-x86
            type=semver,pattern={{major}},suffix=-x86
            type=sha,suffix=-x86
      - name: Docker meta arm
        id: meta-arm
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/koa/tf-bridge-rust
          tags: |
            type=schedule,suffix=-arm
            type=ref,event=branch,suffix=-arm
            type=ref,event=pr,suffix=-arm
            type=semver,pattern={{version}},suffix=-arm
            type=semver,pattern={{major}}.{{minor}},suffix=-arm
            type=semver,pattern={{major}},suffix=-arm
            type=sha,suffix=-arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push x86
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-x86.outputs.tags }}
          labels: ${{ steps.meta-x86.outputs.labels }}
          file: Dockerfile.x86
          platforms: linux/amd64
      - name: Build and push arm
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-arm.outputs.tags }}
          labels: ${{ steps.meta-arm.outputs.labels }}
          file: Dockerfile.arm
          platforms: linux/amd64
